
<html>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                <div class="panel-body">
                    <div class="text-center">
                    <h3><i class="fa fa-lock fa-4x"></i></h3>
                    <h2 class="text-center">Forgot Password?</h2>
                    <p>Bạn Có Thể Đổi Lại Mật Khẩu Ở Đây</p>
                    <div class="panel-body">
        
                        <form id="register-form" role="form" autocomplete="off" class="form" method="post" action="<?= $this->url->get('Account/forgotPassWord') ?>">
        
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                                <input id="userName" name="userName" placeholder="Nhập UserName Của Bạn" class="form-control"  type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                                <input id="gmail" name="gmail" placeholder="Nhập Gmail Của Bạn" class="form-control"  type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                                <input id="passWord" name="passWord" placeholder="Nhập PassWord  Mới" class="form-control"  type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                                <input id="rePassWord" name="rePassWord" placeholder="Nhập Lại PassWord  Mới" class="form-control"  type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <button id = "changePsw" class="btn btn-lg btn-primary btn-block" type="button" onclick = "checkUser();"> Đổi Mật Khẩu</button>
                        </div>
                        
                        <input type="hidden" class="hide" name="token" id="token" value=""> 
                        </form>
        
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>


<script>
    function checkUser () {
        console.log(11111);
        if($("#passWord").val() != $("#rePassWord").val()) {
            $("#passWord").css("border","1px red solid");
            $("#rePassWord").css("border","1px red solid");
            alert('Nhập Lại Pass Word Chưa Đúng');
        }
        var data = new Object();
        data.userName = $("#userName").val();
        data.gmail = $("#gmail").val();
        data.passWord = $("#passWord").val();
        $.ajax({
                url: '/devtest/Account/forgotPassWord?validate=true',
                type: 'POST',
                data: data,
                success: function(r){
                    if(r['result'] == 'OK') {
                        $("#register-form").submit();
                    } else {
                        alert('Đổi Mật Khẩu Không Thành Công');
                    }
                }
            });
    }

</script>
</html>