<html>
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>

<form action="<?= $this->url->get('Account/register') ?>" method = "post" id = "formRegister">
  <div class="container">
    <h1>ĐĂNG KÝ</h1>
    <p>Vui lòng điền thông tin của bạn</p>
    <hr>
    
    <label for="name"><b>Họ và Tên</b></label>
    <input type="text" placeholder="Họ và Tên" name="name" id="name" required>

    <label for="birthday"><b>Ngày Sinh</b></label>
    <input type="text" placeholder="Ngày Sinh" name="birthday"  id="birthday" >

    <label for="address"><b>Địa Chỉ</b></label>
    <input type="text" placeholder="Địa Chỉ" name="address"  id="address" >

    <label for="phone"><b>Số Điện Thoại</b></label>
    <input type="text" placeholder="Số Điện Thoại" name="phone" id="phone" >

    <label for="school"><b>Trường Học</b></label>
    <input type="text" placeholder="Trường Học" name="school" id="school" >

    <label for="hobby"><b>Sở Thích</b></label>
    <input type="text" placeholder="Sở Thích" name="hobby" id="hobby" >

    <label for="gmail"><b>Gmail</b></label>
    <input type="text" placeholder="Gmail" name="gmail" id="gmail" >

    <label for="userName"><b>Tên Tài Khoản</b></label>
    <input type="text" placeholder="Tên Tài Khoản" name="userName" id="userName" required>

    <label for="passWord"><b>Mật Khẩu</b></label>
    <input type="password" placeholder="Mật Khẩu" name="password" id="password" required>

    <label for="rePassWord"><b>Xác Nhận Mật Khẩu</b></label>
    <input type="password" placeholder="Xác Nhận Mật Khẩu" name="rePassWord" id="rePassWord" required>
    <hr>
    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

    <button type = "button" id = "submitButton" class="registerbtn" onclick = "validateInfo();">Register</button>
  </div>
  
  <div class="container signin">
    <p>Already have an account? <a href="#">Sign in</a>.</p>
  </div>
</form>


<script>

    
function validateInfo () {
    if($("#password").val() != $("#rePassWord").val()){
        $("#rePassWord").css('border','1px red solid');
        alert('Xác Nhận Mật Khẩu Không Đúng');
        return;
    } else {
        $("#rePassWord").css('border','none');
    }
    $.ajax({
        url: "/devtest/Account/register?validate=true", 
        data: $('form').serializeArray(),
        type: "post", 
        success: function(r){
            if(r['result'] == 'error') {
                $("#userName").css('border','1px red solid');
                alert('Tài Khoản Đã Tồn Tại, Vui Lòng Nhập Lại');
            } else {
                console.log(r['result']);
                $("#formRegister").submit();
            }
        }
    });
}


</script>

</html>
